### PR TITLE
converts csv to on our radar and fixes the thing I've missed in gift guides

### PR DESCRIPTION
**Pull request by milenam**
## WHAT:
converts csv to on our radar and fixes the thing I've missed in gift guides
## HOW TO TEST: 
copy csv from a google doc https://docs.google.com/document/d/1jMfOh6yCw8RxcaoM9G4xQFHCcphZ4Pna25aek28d2Wo/edit

### CODE REVIEW

**Comment by milenam** [comment]
@charliesneath when reading from csv the product info is not on one line, some things just jump to another line. So whenever people copy from csv they have to put each radar-item on one line manually. Otherwise it is pretty much ready to go, please take a look

**Comment by charliesneath** [comment]
@milenam looks great -- going to close this without merging into master since I merged into my main branch, which I'll merge into master later today.

**Comment by charliesneath** [comment]
@milenam NOTE: White this does work, it doesn't use any of the pre-defined templates that you've already created (i.e. nothing from `_includes/templates`).

You mentioned that there were issues getting that to work; I understand there might challenges but we'll likely have to update this code so we can decouple the "On Our Radar" template code from the Javascript.

**Comment by milenam** [comment]
@charliesneath it does use the template from _includes/template, here is a screen shot of the template and a block of code I use in js file. I never mentioned that there were issues with the template. The only thing I said was to import data from csv to google doc correctly, so every item is on it's own line
screen shot 2015-12-11 at 11 09 30 am
screen shot 2015-12-11 at 11 09 17 am

**Comment by milenam** [comment]
@charliesneath may be try to pull, both gift-guides and on-our-radar use the templates from _includes/template

**Pull request closed without merging**
